[package]
name = "pycrdt"
version = "0.12.7"
edition = "2021"

[lib]
name = "pycrdt"
crate-type = ["cdylib"]

[dependencies]
yrs = { version = "0.22.0", features = ["sync"] }

[dependencies.pyo3]
version = "0.23.4"
